# Generated by Django 4.0.2 on 2022-02-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('finishFlg', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
