# Generated by Django 4.0.2 on 2022-02-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('want2studyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymodel',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
