# Generated by Django 4.0.2 on 2022-02-19 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('want2studyApp', '0003_studymodel_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymodel',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
